require File.expand_path('../config/application', __FILE__)
require 'rake'

MarbleApp::Application.load_tasks

task :default => [:test, 'test:acceptance']

require 'rake/testtask'
Rake::TestTask.new('test:acceptance') do |t|
  t.libs << 'test'
  t.pattern = 'test/acceptance/test_*.rb'
end